In [168]:
import pandas as pd

df = pd.read_csv("Datasets\HepatitisCdata.csv")

In [169]:
df.head()

S.no.       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL  \
0      1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93  3.23   
1      2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17  4.80   
2      3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84  5.20   
3      4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33  4.74   
4      5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15  4.32   

    CREA   GGT  PROT  
0  106.0  12.1  69.0  
1   74.0  15.6  76.5  
2   86.0  33.2  79.3  
3   80.0  33.8  75.7  
4   76.0  29.9  68.7

In [170]:
df = df.drop(['S.no.'], axis=1)

In [171]:
df.head()

Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA  \
0  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0   
1  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0   
2  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0   
3  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0   
4  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0   

    GGT  PROT  
0  12.1  69.0  
1  15.6  76.5  
2  33.2  79.3  
3  33.8  75.7  
4  29.9  68.7

In [172]:
df["Sex"].unique()

array(['m', 'f'], dtype=object)

In [173]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
df["Sex"] = le_sex.fit_transform(df['Sex'])
df["Sex"].unique()

array([1, 0])

In [174]:
df["Category"].unique()

array(['0=Blood Donor', '0s=suspect Blood Donor', '1=Hepatitis',
       '2=Fibrosis', '3=Cirrhosis'], dtype=object)

In [175]:
from sklearn.preprocessing import LabelEncoder
le_Category = LabelEncoder()
df["Category"] = le_sex.fit_transform(df['Category'])
df["Category"].unique()

array([0, 1, 2, 3, 4])

In [176]:
df = df.dropna()
df.isnull().sum()

Category    0
Age         0
Sex         0
ALB         0
ALP         0
ALT         0
AST         0
BIL         0
CHE         0
CHOL        0
CREA        0
GGT         0
PROT        0
dtype: int64

In [177]:
df.head()

Category  Age  Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  \
0         0   32    1  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1   
1         0   32    1  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6   
2         0   32    1  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2   
3         0   32    1  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8   
4         0   32    1  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9   

   PROT  
0  69.0  
1  76.5  
2  79.3  
3  75.7  
4  68.7

In [178]:
x= df.drop("Category", axis=1)
y= df["Category"]

In [179]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(x, y.values)

LinearRegression()

In [180]:
y_pred = linear_reg.predict(x)

In [181]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))

In [182]:
error

0.6518519585365149

In [186]:
x = np.array([[51,'m', 43,37.2,21.4, 132.8, 5, 10, 23, 45, 66, 12]])
x

array([['51', 'm', '43', '37.2', '21.4', '132.8', '5', '10', '23', '45',
        '66', '12']], dtype='<U32')

In [187]:
x[:, 1] = le_sex.transform(x[:,1])
x = X.astype(float)
x

ValueError: y contains previously unseen labels: 'm'

In [164]:
y_pred = linear_reg.predict(x)


C:\Users\Sikandar\anaconda3\envs\ml\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.

In [104]:
import pickle

In [106]:
data= {'model': linear_reg, 'le_Category': le_Category, 'le_sex': le_sex}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data,file)

In [107]:
with open('saved_steps.pkl', 'rb') as file:
    data= pickle.load(file)
    
linear_Reg= data['model']
le_Category= data['le_Category']
le_sex= data['le_sex']

In [110]:
y_pred = linear_Reg.predict(x)
y_pred.astype(int)

C:\Users\Sikandar\anaconda3\envs\ml\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0])